add migration job

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -267,23 +267,43 @@ jobs:
       - destroy-environment:
           ID: ${CIRCLE_WORKFLOW_ID}
 
-#
-#  run-migrations:
-#    docker:
-#      # Docker image here that supports NodeJS
-#    steps:
-#      # Checkout code from git
-#      - run:
-#          name: Run migrations
-#          command: |
-#            # Your code here
-#            exit 1
-#      - run:
-#          name: Send migration results to memstash
-#          command: |
-#            # Your code here
-#            exit 1
-#     # Here's where you will add some code to rollback on failure      
+
+  run-migrations:
+    docker:
+      # Docker image here that supports NodeJS
+      circleci/node:13.8.0
+    steps:
+      # Checkout code from git
+      - checkout
+      - run:
+          name: Run migrations
+          command: |
+            # Your code here
+            echo "NODE_ENV=local" > "backend/.env"
+            echo "VERSION=1" >> "backend/.env"
+            echo "TYPEORM_CONNECTION=postgres" >> "backend/.env"
+            echo "TYPEORM_MIGRATIONS_DIR=./src/migrations" >> "backend/.env"
+            echo "TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts" >> "backend/.env"
+            echo "TYPEORM_MIGRATIONS=./src/migrations/*.ts" >> "backend/.env"
+
+            # Things you can change if you wish...
+            echo "TYPEORM_HOST=${TYPEORM_HOST}" >> "backend/.env"
+            echo "TYPEORM_PORT=5532" >> "backend/.env"
+            echo "TYPEORM_USERNAME=${TYPEORM_USERNAME}" >> "backend/.env"
+            echo "TYPEORM_PASSWORD=${TYPEORM_PASSWORD}" >> "backend/.env"
+            echo "TYPEORM_DATABASE=${TYPEORM_DATABASE}" >> "backend/.env"
+
+            cd backend
+            sudo npm run migrations > migration.log
+            cat migration.log
+
+            exit 1
+      - run:
+          name: Send migration results to memstash
+          command: |
+            # Your code here
+            exit 1
+     # Here's where you will add some code to rollback on failure      
 #
 #  deploy-frontend:
 #    docker:
@@ -394,14 +414,14 @@ workflows:
 #          requires: [build-backend]
 #      - scan-frontend:
 #          requires: [build-frontend]
-      - deploy-infrastructure
+#      - deploy-infrastructure
 #          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
 #          filters:
 #            branches:
 #              only: [test-feature-branch]
-      - configure-infrastructure:
-          requires: [deploy-infrastructure]
-#      - run-migrations:
+#      - configure-infrastructure:
+#          requires: [deploy-infrastructure]
+      - run-migrations
 #          requires: [configure-infrastructure]
 #      - deploy-frontend:
 #          requires: [run-migrations]
